name: Build ISO

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install build-essential libbsd-dev pkg-config openjdk-8-jdk-headless openjdk-11-jdk-headless

    - name: Softlink directories
      run: |
        ln -s /usr/lib/jvm/java-8-openjdk-amd64 host/jdk8
        ln -s /usr/lib/jvm/java-11-openjdk-amd64 host/jdk11

    - name: Make
      run: |
        make -C host/src/makefs_termux
        make -C host/src/makefs_termux install DESTDIR=$PWD/host
        make -C target
        make -C samples/helloworld
        make -C samples/ps5-app0-filedump
        make -C samples/ps5-sandbox-filedump
        make -C samples/ps5-invoke-native

    - name: Upload ps5-invoke-native artifact
      uses: actions/upload-artifact@v3
      with:
        path: samples/ps5-invoke-native/*.iso
        name: ps5-invoke-native
	
    - name: Upload ps5-sandbox-filedump artifact
      uses: actions/upload-artifact@v3
      with:
        path: samples/ps5-sandbox-filedump/*.iso
        name: ps5-sandbox-filedump

    - name: Upload ps5-app0-filedump
      uses: actions/upload-artifact@v3
      with:
        path: samples/ps5-app0-filedump/*.iso
        name: ps5-app0-filedump

    - name: Upload helloworld
      uses: actions/upload-artifact@v3
      with:
        path: samples/helloworld/*.iso
        name: helloworld
